{% set name = "bashplotlib" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1b59be49d6254a5bd808919e0a23a75a703a02e7e84478edda765714e0bfaee 

build:
  noarch: python
  number: 1
  entry_points:
    - hist=bashplotlib.histogram:main
    - scatter=bashplotlib.scatterplot:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - bashplotlib
    - bashplotlib.utils
  commands:
    - hist --help
    - scatter --help

about:
  home: https://github.com/glamp/bashplotlib
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: plotting in the terminal
  description: |
     bashplotlib is a python package and command line tool for making 
     basic plots in the terminal. It's a quick way to visualize data when 
     you don't have a GUI. It's written in pure python and can quickly 
     be installed anywhere using pip.
  doc_url: https://github.com/glamp/bashplotlib 
  dev_url: https://github.com/glamp/bashplotlib 

extra:
  recipe-maintainers:
    - CurtLH 
