travis:
  secure:
    BINSTAR_TOKEN: TZS+L+QVqODOfmcA+ctp/ApyxiTcE2h1AtHGeKbygfFgbjN0WhIzkOQOjNqjM8N7BJ8xNLB7jTg/d2ocl4+rpZrxMHb9SnKmLk4qgWGkUDK/FlqoyQ84B5AlAGtCuo2g0vT2Q4t6e4gsov1mX2ezI7zk46qdRU+hwLOH2lGktxb54i3q0Tf27lPz0eY/tajC4LR0uSxRbHzYK1galo1XE63CELPOtoo6v6D62Y5ElW27p/67/uWGwdLOB1B3LNKALsYlQzocBeU5n4tsj5BYg7WFYvzR9wMT6N+ORk29JkJVBA13M5hlLOYKbd6u+oNcWXtsTWKHl5ERXq3KbClIY4M99zaS9Obr6b/yjJS6r8/v5e+OU9xMT88IUtPjSXjPsag+NqDjeUAvY5joZcqQOl97NnwVvUyb3mUvJOqHBaNhKIDCyhcrzmcgCenApLOIWHdFBea9MYatEtvCsNtXkUm6BnLrVd5H2vs+XgUvO/+pVO/ZTG+LEEh9+lqTzJjmG/yofGLDzkIaAyMTuc1+12OSfyLN+QBbZGvhPDcdvacCiXZuRg+pZCHJmloMm+W+w39u5b3j6dudwOF0+zxz9Tnqt2IZxmMOxArJZ0+Nv8d+PvlVLr7lcTn28V4Gb6E9RxB35C5Cm3X1MTEwWRrFaJ2ounwhSXzrNHWNpcHsoWw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
